_target_: src.models.bert_parscit_module.BertParsCitLitModule
lr: 2e-5

model:
  _target_: src.models.components.bert_token_classifier.BertTokenClassifier
  model_checkpoint: "allenai/scibert_scivocab_uncased"
  cache_dir: "./cache/"
