_target_: src.models.cora_module.CoraLitModule
lr: 2e-5

model:
  _target_: src.models.components.bert_parscit_finetuner.BertParsCitFineTuner
  model_checkpoint: "/ssd1/jiahe/pretrained/scibert-synthetic-uncased-full-100k"
  output_size: 13
  cache_dir: "/ssd1/jiahe/parscit/"
