_target_: src.datamodules.bert_parscit_datamodule.BertParsCitDataModule

data_repo: "myvision/yuanchuan-synthetic-dataset-final"
batch_size: 8
train_val_test_split: [100_000, 5_000, 10_000]
num_workers: 0
pin_memory: False
data_cache_dir:  "/data3/jiahe/synthetic-final/"
