# @package _global_

hydra:
  run:
    dir: /ssd1/jiahe/logs/debugs/runs/${name}/${now:%Y-%doc2json-%d}_${now:%H-%M-%S}
  sweep:
    dir: /ssd1/jiahe/logs/debugs/multiruns/${name}/${now:%Y-%doc2json-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}
