# @package _global_

hydra:
  run:
    dir: /data3/jiahe/logs/experiments/runs/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
  sweep:
    dir: /data3/jiahe/logs/experiments/multiruns/${name}/${now:%Y-%m-%d}_${now:%H-%M-%S}
    subdir: ${hydra.job.num}
